### ISSUE TITLE
error flag redefined

### ISSUE THREAD

**Issue by ylmcr7** [kubernetes/client-go#1142]
i use client-go simple main.go appear err when second call it
2022-08-04T10:09:43.269+0800    ERROR   logger/logger.go:123    [Recovery from panic]   {"error": "/var/folders/f8/tg5jqs1147x14m2h6h19jr4w0000gn/T/go-build1458861330/b001/exe/main flag redefined: kubeconfig", "request": "

**Comment by triceras** [comment]
Facing the same issue when making a second API request from a gin GET request.
`/var/folders/lb/4znck4ns5xz0fdhtq0chgff80000gp/T/go-build3118074099/b001/exe/main flag redefined: kubeconfig


2022/11/08 16:48:58 [Recovery] 2022/11/08 - 16:48:58 panic recovered:
GET /get_namespaces HTTP/1.1
Host: localhost:8080
Accept: */*
User-Agent: curl/7.79.1


/var/folders/lb/4znck4ns5xz0fdhtq0chgff80000gp/T/go-build3118074099/b001/exe/main flag redefined: kubeconfig
/opt/homebrew/Cellar/go/1.18.3/libexec/src/flag/flag.go:879 (0x100f66623)
        (*FlagSet).Var: panic(msg) // Happens only if flags are declared with identical names
/opt/homebrew/Cellar/go/1.18.3/libexec/src/flag/flag.go:762 (0x100f6631f)
        (*FlagSet).StringVar: f.Var(newStringValue(value, p), name, usage)
/opt/homebrew/Cellar/go/1.18.3/libexec/src/flag/flag.go:775 (0x100f662c4)
        (*FlagSet).String: f.StringVar(p, name, value, usage)
/opt/homebrew/Cellar/go/1.18.3/libexec/src/flag/flag.go:782 (0x101af2ee3)
        String: return CommandLine.String(name, value, usage)
/Users/rafaelabdalla/Documents/coding/Golang/secret_interface/backend/namespaces.go:47 (0x101af2e5c)
        GetNamespaces: kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
/Users/rafaelabdalla/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0x1010f820f)
        (*Context).Next: c.handlers[c.index](c)
/Users/rafaelabdalla/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/recovery.go:101 (0x1010f81f0)
        CustomRecoveryWithWriter.func1: c.Next()
/Users/rafaelabdalla/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0x1010f747f)
        (*Context).Next: c.handlers[c.index](c)
/Users/rafaelabdalla/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/logger.go:240 (0x1010f745c)
        LoggerWithConfig.func1: c.Next()
/Users/rafaelabdalla/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/context.go:173 (0x1010f65e7)
        (*Context).Next: c.handlers[c.index](c)
/Users/rafaelabdalla/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:616 (0x1010f62bc)
        (*Engine).handleHTTPRequest: c.Next()
/Users/rafaelabdalla/go/pkg/mod/github.com/gin-gonic/gin@v1.8.1/gin.go:572 (0x1010f5ed7)
        (*Engine).ServeHTTP: engine.handleHTTPRequest(c)
/opt/homebrew/Cellar/go/1.18.3/libexec/src/net/http/server.go:2916 (0x100e2c07b)
        serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
/opt/homebrew/Cellar/go/1.18.3/libexec/src/net/http/server.go:1966 (0x100e2779b)
        (*conn).serve: serverHandler{c.server}.ServeHTTP(w, w.req)
/opt/homebrew/Cellar/go/1.18.3/libexec/src/runtime/asm_arm64.s:1263 (0x100c00623)
        goexit: MOVD    R0, R0  // NOP`

**Comment by nurhun** [comment]
/reopen I'm facing the same issue with the second request, I had to restart the server for each request when using out-of-cluster config snippet here https://github.com/kubernetes/client-go/blob/master/examples/out-of-cluster-client-configuration/main.go

```
2023/03/28 20:29:05 http: panic serving 127.0.0.1:43550: /home/nurhun/project/__debug_bin flag redefined: kubeconfig
goroutine 10 [running]:
net/http.(*conn).serve.func1()
usr/local/go/src/net/http/server.go:1825 +0x148
panic({0x20bc8e0, 0xc0001910c0})
	/usr/local/go/src/runtime/panic.go:844 +0x25a
flag.(*FlagSet).Var(0xc00007c1e0, {0x2557120, 0xc000190fc0}, {0x23b1a0a, 0xa}, {0x23ee655, 0x2f})
	/usr/local/go/src/flag/flag.go:879 +0x3d9
flag.(*FlagSet).StringVar(0xc00007c1e0, 0xc000190fc0, {0x23b1a0a, 0xa}, {0xc0004161e0, 0x19}, {0x23ee655, 0x2f})
	/usr/local/go/src/flag/flag.go:762 +0x8c
flag.(*FlagSet).String(0xc00007c1e0, {0x23b1a0a, 0xa}, {0xc0004161e0, 0x19}, {0x23ee655, 0x2f})
	/usr/local/go/src/flag/flag.go:775 +0x95
flag.String({0x23b1a0a, 0xa}, {0xc0004161e0, 0x19}, {0x23ee655, 0x2f})
	/usr/local/go/src/flag/flag.go:782 +0x6b
main.(*Kube).ConnectLocal(0xc00000e108)
	/home/nurhun/project/kube.go:39 +0x15d
main.(*Kube).SelectConnection(0xc00000e108)
	/home/nurhun/project/kube.go:78 +0x48
main.getSystemTestEnvList({0x2568288, 0xc0005c6000}, 0xc0005c2200)
	/home/nurhun/project/main.go:1128 +0x4f
net/http.HandlerFunc.ServeHTTP(0x249fbe0, {0x2568288, 0xc0005c6000}, 0xc0005c2200)
	/usr/local/go/src/net/http/server.go:2084 +0x43
main.BasicAuthMiddleware.func1({0x2568288, 0xc0005c6000}, 0xc0005c2200)
	/home/nurhun/project/main.go:1195 +0x21e
net/http.HandlerFunc.ServeHTTP(0xc00000e0f0, {0x2568288, 0xc0005c6000}, 0xc0005c2200)
	/usr/local/go/src/net/http/server.go:2084 +0x43
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00011e540, {0x2568288, 0xc0005c6000}, 0xc0005c2200)
	/home/nurhun/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x25d
net/http.serverHandler.ServeHTTP({0xc0004b41c0}, {0x2568288, 0xc0005c6000}, 0xc0005c2000)
	/usr/local/go/src/net/http/server.go:2916 +0x474
net/http.(*conn).serve(0xc000286be0, {0x2568d38, 0xc0003df000})
	/usr/local/go/src/net/http/server.go:1966 +0x193c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3071 +0x9cf
```
