### ISSUE TITLE
Emutale kubectl apply error

### ISSUE THREAD

**Issue by astingengo** [kubernetes/client-go#1192]
Based on this link: https://github.com/kubernetes/client-go/issues/216
I ended up having the call as 
```
var ctx context.Context
var c client.Client
var actionFn ForEachObjectInYAMLActionFunc

func main() {

	yamlFile, err := ioutil.ReadFile("crds.yaml")
	if err != nil {
		log.Printf("yamlFile.Get err   #%v ", err)
	}

	err = ForEachObjectInYAML(ctx, c, yamlFile, "default", actionFn)
	if err != nil {
		fmt.Println(err)
	}
}
```
but it is failing because of 
```
if err := actionFn(ctx, c, obj); err != nil {
	return err
}
```
the errror is
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10ac5cc]

goroutine 1 [running]:
main.ForEachObjectInYAML({0x0, 0x0}, {0x0, 0x0}, {0xc000880000?, 0xc0000021a0?, 0x200000003?}, {0x12bf20f, 0x7}, 0x0)
       apply.go:125 +0x12c
main.main()
       apply.go:34 +0xc5
exit status 2
``` 
any idea please where I'm missing/doing wrong?

**Comment by roelarents** [comment]
You don't have an actual implementation of `ForEachObjectInYAMLActionFunc`, your `actionFn` is empty cq nil.
