### ISSUE TITLE
invalid memory address or nil pointer dereference on go 1.20.1

### ISSUE THREAD

**Issue by yabanci** [kubernetes/client-go#1229]
Upgrading to go 1.20.1 from 1.19.6, I am getting this error during testing

```
E0217 10:11:44.300188   21635 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 158 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x2c0ed00?, 0x4b09660?})
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:74 +0xf0
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0001df8e8?})
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:48 +0xb0
panic({0x2c0ed00, 0x4b09660})
	/opt/go/src/runtime/panic.go:890 +0x263
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001d27e0, 0xc0001d6630, 0xc000d7c5a0, 0xc0001dfb40)
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001d27e0, 0xc000d7c5a0)
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:361 +0x2f9
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001001ee0)
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:155 +0x49
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0001c21c0?, {0x3905c00, 0xc0006d4780}, 0x1, 0xc000d7c5a0)
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001d27e0, 0xc000d7c5a0)
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:220 +0x2aa
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:73 +0x74
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:71 +0xe5
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference

goroutine 158 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0001df8e8?})
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:55 +0x145
panic({0x2c0ed00, 0x4b09660})
	/opt/go/src/runtime/panic.go:890 +0x263
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0001d27e0, 0xc0001d6630, 0xc000d7c5a0, 0xc0001dfb40)
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:319 +0x127a
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0001d27e0, 0xc000d7c5a0)
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:361 +0x2f9
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:221 +0x45
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001001ee0)
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:155 +0x49
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0001c21c0?, {0x3905c00, 0xc0006d4780}, 0x1, 0xc000d7c5a0)
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:156 +0xcf
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0001d27e0, 0xc000d7c5a0)
	/code/.cache/gopath/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:220 +0x2aa
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:56 +0x3f
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:73 +0x74
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/code/.cache/gopath/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:71 +0xe5
```

using client-go and apimachinery v0.23.0. go 1.19.6 works without a problem. The panic trace doesn't include anything from the tested code so not sure how to troubleshoot.

**Comment by vvxxvvxx** [comment]
I got the same error/crash when adding `c.informer.Run(stopCh)`. (`_, informer=cache.NewInformer(...)`). if removing `c.informer.Run(stopCh)`, there is no crash. go version I am using is 1.20. apimachinery is 0.27.1
this error shows twice. I pasted once as below.
```

goroutine 20 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2540be400?})
        /usr/local/go/pkg/mod/k8s.io/apimachinery@v0.27.1/pkg/util/runtime/runtime.go:56 +0xd7
panic({0x1726500, 0x2718f00})
        /usr/local/go/src/runtime/panic.go:884 +0x213
k8s.io/client-go/tools/cache.(*Reflector).list(0xc00012a000, 0xc0000ab2c0)
        /usr/local/go/pkg/mod/k8s.io/client-go@v0.27.1/tools/cache/reflector.go:528 +0xb72
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc00012a000, 0xc0000ab2c0)
        /usr/local/go/pkg/mod/k8s.io/client-go@v0.27.1/tools/cache/reflector.go:346 +0x22c
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
        /usr/local/go/pkg/mod/k8s.io/client-go@v0.27.1/tools/cache/reflector.go:289 +0x26
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x10?)
        /usr/local/go/pkg/mod/k8s.io/apimachinery@v0.27.1/pkg/util/wait/backoff.go:226 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000332080?, {0x1b54100, 0xc000468000}, 0x1, 0xc0000ab2c0)
        /usr/local/go/pkg/mod/k8s.io/apimachinery@v0.27.1/pkg/util/wait/backoff.go:227 +0xb6
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc00012a000, 0xc0000ab2c0)
        /usr/local/go/pkg/mod/k8s.io/client-go@v0.27.1/tools/cache/reflector.go:288 +0x17d
k8s.io/apimachinery/pkg/util/wait.(*Group).StartWithChannel.func1()
        /usr/local/go/pkg/mod/k8s.io/apimachinery@v0.27.1/pkg/util/wait/wait.go:55 +0x22
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1()
        /usr/local/go/pkg/mod/k8s.io/apimachinery@v0.27.1/pkg/util/wait/wait.go:72 +0x5a
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
        /usr/local/go/pkg/mod/k8s.io/apimachinery@v0.27.1/pkg/util/wait/wait.go:70 +0x85
```
