### ISSUE TITLE
Cannot access *ObjectReference property

### ISSUE THREAD

**Issue by iordaniordanov** [kubernetes/client-go#218]
Here is the case. I'm listing all Endpoints and trying to map the info I get form them. I'm stuck at the PodName, which should be in the ```Name``` property of ```TargetRef```. [Docs](https://godoc.org/k8s.io/client-go/pkg/api/v1#EndpointAddress)
Some code:
This works
```
endPoints, _ := clientset.CoreV1().Endpoints("").List(metav1.ListOptions{})
        for _, v := range endPoints.Items {
                fmt.Println(v.Name)
                for _, e := range v.Subsets {
                        for _, a := range e.Addresses {
                                fmt.Println("Address")
                                fmt.Println(a.IP)
                                fmt.Println("===================")
                                fmt.Println("Pod")
                                fmt.Println(a.TargetRef)
                                fmt.Println("===================")}

                        for _, p := range e.Ports {
                                fmt.Println("Port")
                                fmt.Println(p.Port)
                                fmt.Println("==============")}
                }}
Result:

Pod
&ObjectReference{Kind:Pod,Namespace:default,Name:my-nginx-858393261-cwwp6,UID:<UID>,APIVersion:,ResourceVersion:127010,FieldPath:,}

```
But changing to this does not
```
fmt.Println(a.TargetRef.Name)

Result:
Pod
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1313d8e]

goroutine 1 [running]:
main.notify(0xc42021f3a0, 0xd, 0xc420655f50)
	/home/jordan/cloud-apps/cloud-apps/k8s/k8s-monitor/monitor/main.go:173 +0x5fe
main.main()
	/home/jordan/cloud-apps/cloud-apps/k8s/k8s-monitor/monitor/main.go:249 +0x13f

```

**Comment by iordaniordanov** [comment]
I'm using HEAD

**Comment by iordaniordanov** [comment]
Any update ?

**Comment by lavalamp** [comment]
It is a pointer. You need to check that it is not null before accessing it.
The API doesn't guarantee that the Name field is always set for an object
reference.

**Comment by iordaniordanov** [comment]
Ahh, silly me. Thanks!
Closing the issue.
