### ISSUE TITLE
client-go broke for 1.6 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/client-go#239]
Hi I wanted to upgrade [K8Guard](https://github.com/k8guard) (an auditing system for kubernetes) to work with k8s 1.6. 

we were using client-go `v2.0.0-alpha.1` with  `k8s 1.5`
I did notice the API calls have changed and I updated client-go to `v3.0.0-beta.0`

and I changed my code to look like this
```
// NEW CODE FOR v3.0.0-beta.0 THAT DOESNT WORK
import (
	"strings"
	"io/ioutil"
	"encoding/json"
	meta "k8s.io/apimachinery/pkg/apis/meta/v1"
	lib "github.com/k8guard/k8guardlibs"
	"k8s.io/client-go/pkg/apis/apps/v1beta1"
	"github.com/k8guard/k8guardlibs/messaging/kafka"
	"github.com/k8guard/k8guardlibs/violations"
	"github.com/k8guard/k8guard-discover/metrics"
	"github.com/prometheus/client_golang/prometheus"
)

func GetAllDeployFromApi() []v1beta1.Deployment {
	deploys, err := Clientset.AppsV1beta1().Deployments(lib.Cfg.Namespace).List(meta.ListOptions{})
	if err != nil {
		lib.Log.Error("error: ", err)
		panic(err.Error())
	}

...
...
...
	return deploys.Items
```

for previous version ( `v2.0.0-alpha.1` with 1.5 k8s) the code was this:
https://github.com/k8guard/k8guard-discover/blob/cd95898cb406bba14bc327899e4309b0430f9843/discover/deployments.go

```
// OLD CODE FOR v2.0.0-alpha.1 THAT WORKS
package discover
 
import (
    "strings"
    "io/ioutil"
    "encoding/json"
    "k8s.io/client-go/pkg/api/v1"
    lib "github.com/k8guard/k8guardlibs"
    "k8s.io/client-go/pkg/apis/extensions/v1beta1"
    "github.com/k8guard/k8guardlibs/messaging/kafka"
    "github.com/k8guard/k8guardlibs/violations"
    "github.com/k8guard/k8guard-discover/metrics"
    "github.com/prometheus/client_golang/prometheus"
)
 
func GetAllDeployFromApi() []v1beta1.Deployment {
    deploys, err := Clientset.Deployments(lib.Cfg.Namespace).List(v1.ListOptions{})
    if err != nil {
        lib.Log.Error("error: ", err)
        panic(err.Error())
    }
...
...
...

    return deploys.Items
}
```

and the error I get is:

```
2017/07/11 20:07:18 [k8guard-discover-deployment-2727519787-fcb08/k4v1x7jbjT-000038] "GET http://192.168.99.100:32243/deploys HTTP/1.1" from 172.17.0.1:49460 - panic: runtime error: invalid memory address or nil pointer dereference
2017/07/11 20:07:18 goroutine 94 [running]:
runtime/debug.Stack(0xc420161600, 0x1f75260, 0xc4200d3b60)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/debug/stack.go:24 +0x79
github.com/k8guard/k8guard-discover/vendor/github.com/pressly/chi/middleware.Recoverer.func1.1(0xc420161600, 0x7f305859fdd0, 0xc4200fe7c0)
	/Users/z001r9y/go/src/github.com/k8guard/k8guard-discover/vendor/github.com/pressly/chi/middleware/recoverer.go:23 +0x82
panic(0x14b2f00, 0x1fd28f0)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/k8guard/k8guard-discover/vendor/k8s.io/client-go/kubernetes/typed/apps/v1beta1.(*deployments).List(0xc42000af80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/z001r9y/go/src/github.com/k8guard/k8guard-discover/vendor/k8s.io/client-go/kubernetes/typed/apps/v1beta1/deployment.go:141 +0x9b
github.com/k8guard/k8guard-discover/discover.GetAllDeployFromApi(0xc42023eff0, 0x165a081, 0x12)
	/Users/z001r9y/go/src/github.com/k8guard/k8guard-discover/discover/deployments.go:17 +0x91
main.startHttpServer.func5(0x7f305859fdd0, 0xc4200fe7c0, 0xc420161700)
	/Users/z001r9y/go/src/github.com/k8guard/k8guard-discover/routes.go:80 +0xaa
net/http.HandlerFunc.ServeHTTP(0x16c0570, 0x7f305859fdd0, 0xc4200fe7c0, 0xc420161700)
```

**Comment by ericchiang** [comment]
Where is Clientset coming from? Your example looks incomplete.

**Comment by medyagh** [comment]
here is my clientset
```
func LoadClientset() (kubernetes.Clientset, error) {
	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	configOverrides := &clientcmd.ConfigOverrides{}
	kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
	config, err := kubeConfig.ClientConfig()
	if err != nil {
		return kubernetes.Clientset{}, errors.New("Failed loading client config")
	}
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return kubernetes.Clientset{}, errors.New("Failed getting clientset")
	}
	return *clientset, nil
}
```
@ericchiang

**Comment by lavalamp** [comment]
Almost certainly the problem is that your clientset has not been initialized. I filed https://github.com/kubernetes/client-go/issues/240

**Comment by lavalamp** [comment]
You should pass `*kubernetes.Clientset`, not `kubernetes.Clientset`. Then you wouldn't have to do the line `return kubernetes.Clientset{}, err`, which will cause the problem you observe if the error is ignored.

**Comment by medyagh** [comment]
@lavalamp I did that, and now all I get is panicing on the loading the client set.
I am doing this in minikube with k8s v1.6.4 

```
func LoadClientset() (*kubernetes.Clientset, error) {
	loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	configOverrides := &clientcmd.ConfigOverrides{}
	kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
	config, err := kubeConfig.ClientConfig()
	if err != nil {
		return &kubernetes.Clientset{}, errors.New("Failed loading client config")
	}
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return &kubernetes.Clientset{}, errors.New("Failed getting clientset")
	}
	return clientset, nil
}
```

```
func init() {
	Clientset, err = k8s.LoadClientset()

	if err != nil {
		lib.Log.Error("error loading ClientSet ", err)
		panic(err)
	}
	
}
```

**Comment by medyagh** [comment]
@lavalamp is there a chance the client-go library only works on k8s 1.7 ?

**Comment by medyagh** [comment]
@lavalamp is a kubeconfig file required in the latest client-go ?
previously if the pod was running in a namespace with enough permission (like the way it is in minikube) it would not need to give a kubeconfig file.

**Comment by medyagh** [comment]
ok I solved the problem, for anyone who reads this in the future.
other than all the API changes I had to change the way I connect to the Clientset too. the commented part is old way, the rest is new way.

```
	//loadingRules := clientcmd.NewDefaultClientConfigLoadingRules()
	//configOverrides := &clientcmd.ConfigOverrides{}
	//kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
	//config, err := kubeConfig.ClientConfig()
	config, err := rest.InClusterConfig()
	if err != nil {
		return &kubernetes.Clientset{}, errors.New("Failed loading client config")
	}
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		return &kubernetes.Clientset{}, errors.New("Failed getting clientset")
	}
	return clientset, nil
```

**Comment by caesarxuchao** [comment]
@medyagh thanks for the updates. Have you taken a look at the [in-cluster configuration example](https://github.com/kubernetes/client-go/blob/master/examples/in-cluster-client-configuration/main.go#L32-L37)? It didn't change from 1.5 to 1.6.
