### ISSUE TITLE
panic: No Auth Provider found for name "oidc"

### ISSUE THREAD

**Issue by r0fls** [kubernetes/client-go#345]
The out of cluster config example no longer works for me. I believe it was recently so I'm not sure what changed. I get this error:

```
panic: No Auth Provider found for name "oidc"

goroutine 1 [running]:
main.main()
        /Users/raphael.deem/Documents/code/go/src/list-proms/main.go:53 +0x60d
```

I am able to list the nodes:

```
$ kubectl get nodes | wc -l
      10
```

I tried doing https://github.com/coreos/tectonic-forum/issues/99#issuecomment-295458740

But then I just get this, as expected:

```
$ go build                                                                                       
# _/Users/raphael.deem/Documents/code/list-proms                                                                      
./main.go:14:2: imported and not used: "k8s.io/client-go/plugin/pkg/client/auth/oidc"   
```

**Comment by ericchiang** [comment]
The format is

```
import (
     _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"
)
```

**Comment by r0fls** [comment]
whoops, thank you!
