### ISSUE TITLE
Segmentation violation while creating a service

### ISSUE THREAD

**Issue by w0mbat** [kubernetes/client-go#5]
I have been successfully able to get a service by name, but I am running into a segmentation violation while I create a service.

This is the function is created:

```
func createService(namespace string, serviceName string, servicePort int32) {
    fmt.Println("Service '", serviceName, "' in namespace '", namespace, "' does not exist!")
    metadata := v1.ObjectMeta{Name: serviceName, Namespace: namespace}

    servicePorts := []v1.ServicePort{v1.ServicePort{Port: servicePort}}
    serviceSpec := v1.ServiceSpec{Ports: servicePorts}

    service := v1.Service{ObjectMeta: metadata, Spec: serviceSpec}

    clientset.Core().Services(namespace).Create(&service)
}
```

This is the stacktrace I get related to client-go:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4913d0]

goroutine 1 [running]:
panic(0xd6af80, 0xc42000c0c0)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
k8s.io/client-go/1.4/kubernetes/typed/core/v1.(*services).Create(0xc42028b8c0, 0xc420426780, 0x7, 0x1538040, 0xc42028b8c0)
    /Users/wombat/golang/src/k8s.io/client-go/1.4/kubernetes/typed/core/v1/service.go:62 +0x70
```

**Comment by bboreham** [comment]
The error message and the [location of the crash](https://github.com/kubernetes/client-go/blob/master/1.4/kubernetes/typed/core/v1/service.go#L62) suggest that the `client` member of the `services` struct was nil.

You don't show where you got `clientset` from; could it perhaps be nil?

**Comment by lavalamp** [comment]
Didn't see this until just now, but yes, I recommend looking at where the clientset is constructed.

**Comment by w0mbat** [comment]
sorry guys - I did a local assignment `:=` instead of `=`
