### ISSUE TITLE
How to properly stop and cleanup EventBroadcaster

### ISSUE THREAD

**Issue by relyt0925** [kubernetes/client-go#649]
Our service interacts with many different Kuberentes clusters and creates event broadcasters against each of the API Servers when it's performing actions and then once done expects to cleanup the broadcaster entirely to make sure there are no leaks. 

```
import (
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/tools/record"

	"k8s.io/api/core/v1"
	"k8s.io/client-go/kubernetes/scheme"
	v1core "k8s.io/client-go/kubernetes/typed/core/v1"
)

// NewEventRecorder returns a new Event recorder
func NewEventRecorder(clientset *kubernetes.Clientset, namespace string, publisherID string) (record.EventRecorder, func(), error) {
	broadcaster := record.NewBroadcaster()
	shutdownInterface := broadcaster.StartRecordingToSink(&v1core.EventSinkImpl{Interface: v1core.New(clientset.CoreV1().RESTClient()).Events(namespace)})
	return broadcaster.NewRecorder(scheme.Scheme, v1.EventSource{Component: publisherID}), func() { shutdownInterface.Stop() }, nil
}
```

What we are seeing that despite calling Stop() below the loop goroutine hangs around indefinitetly 

```
goroutine 89892 [chan receive, 810 minutes]:
github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc015ad8440)
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 182245 [chan receive, 324 minutes]:
github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc07dbaa380)
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 88795 [chan receive, 816 minutes]:
github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc00d85f040)
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc

goroutine 96642 [chan receive, 774 minutes]:
github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.(*Broadcaster).loop(0xc00e89bf00)
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:207 +0x66
created by github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch.NewBroadcaster
	/go/src/github.ibm.com/alchemy-containers/armada-bootstrap/vendor/k8s.io/apimachinery/pkg/watch/mux.go:75 +0xcc
```

It appears it might be waiting to force the events through but I believe there ultimately needs to be a way to do a complete shutdown and not wait for the events to go through or that it at least shuts down after some period of time so resource leaks don't occur

**Comment by relyt0925** [comment]
Almost effectively looking for a ForceShutdown in the case where events aren't critical to be delivered and instead are just best effort. 
```
func (m *Broadcaster) Shutdown() {
```

```
func (m *Broadcaster) ForceShutdown() {

```

**Comment by mattmoor** [comment]
@relyt0925 I'm curious if you got an answer to this?  I was just battling something along these lines myself.
