### ISSUE TITLE
go client for gke crashes with round trip

### ISSUE THREAD

**Issue by collbrain** [kubernetes/client-go#865]
Hi.

GKE Version: 1.15.2

Try to talk to my gke server using api's and getting following error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa2194f]

goroutine 1 [running]:
k8s.io/client-go/plugin/pkg/client/auth/gcp.(*conditionalTransport).RoundTrip(0xc00035fea0, 0xc000658d00, 0x1c8933b, 0xa, 0xc0000bdac0)
        /home/collbrain/workspace/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/plugin/pkg/client/auth/gcp/gcp.go:377 +0xcf
k8s.io/client-go/transport.(*userAgentRoundTripper).RoundTrip(0xc00035fec0, 0xc000658c00, 0xc00035fec0, 0xbfcdf0cf31b95295, 0x827fe2502)
        /home/collbrain/workspace/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/transport/round_trippers.go:167 +0x1d6
net/http.send(0xc000658b00, 0x1eedb40, 0xc00035fec0, 0xbfcdf0cf31b95295, 0x827fe2502, 0x2a8cda0, 0xc0000111c0, 0xbfcdf0cf31b95295, 0x1, 0x0)
        /usr/local/go/src/net/http/client.go:252 +0x453
net/http.(*Client).send(0xc000361e90, 0xc000658b00, 0xbfcdf0cf31b95295, 0x827fe2502, 0x2a8cda0, 0xc0000111c0, 0x0, 0x1, 0xc0004afdf0)
        /usr/local/go/src/net/http/client.go:176 +0xff
net/http.(*Client).do(0xc000361e90, 0xc000658b00, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/client.go:718 +0x45f
net/http.(*Client).Do(0xc000361e90, 0xc000658b00, 0x0, 0x1f304e0, 0xc000369860)
        /usr/local/go/src/net/http/client.go:586 +0x35
k8s.io/client-go/rest.(*Request).request(0xc000001e00, 0xc0007e7550, 0x0, 0x0)
        /home/collbrain/workspace/pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/rest/request.go:737 +0x37f
k8s.io/client-go/rest.(*Request).Do(0xc000001e00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
```

How to resolve this issue?

**Comment by oze4** [comment]
I get this same error after updating to the latest version of Go.
