### ISSUE TITLE
Dynamic fake client usage: cannot deep copy []map[string]interface

### ISSUE THREAD

**Issue by ahstn** [kubernetes/client-go#913]
**Issue:**
When using the [k8s.io/client-go/dynamic/fake](https://github.com/kubernetes/client-go/blob/v0.18.12/dynamic/fake/simple.go) simple client, it seems to error out if the unstructured "Object" field contains any `[]map[string]interface{}` (i.e. volumes or containers in a PodSpec).

```
panic: cannot deep copy []map[string]interface {} [recovered]
	panic: cannot deep copy []map[string]interface {}
```

I've tried using the same spec as in [examples/dynamic-create-update-delete-deployment](https://github.com/kubernetes/client-go/blob/v0.18.12/examples/dynamic-create-update-delete-deployment/main.go#L69), but it results in the same issue with the fake client.

**Example snippet to reproduce:**
```go
import (
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/dynamic/fake"
	"testing"
	"time"
)

func TestResourcesInUse(t *testing.T) {
	scheme := runtime.NewScheme()

	fake.NewSimpleDynamicClient(scheme, newPodWithVolumes("config-pod", "properties", "tokens"))
}

func newPodWithVolumes(name, config, secret string) *unstructured.Unstructured {
	return &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": "v1",
			"kind":       "pod",
			"metadata": map[string]interface{}{
				"namespace": "default",
				"name":      name,
				"creationTimestamp": time.Now().Format(time.RFC3339),
			},
			"spec": map[string]interface{}{
				"containers": []map[string]interface{}{
					{
						"name": name,
					},
				},
			},
			"volumes": []map[string]interface{}{
				{
					"name": secret,
					"secret": map[string]interface{}{
						"secretName": secret,
					},
				},
				{
					"name": config,
					"configMap": map[string]interface{}{
						"name": config,
					},
				},
			},
		},
	}
}
```

**Full stack trace:**
```
--- FAIL: TestResourcesInUse (0.00s)
panic: cannot deep copy []map[string]interface {} [recovered]
	panic: cannot deep copy []map[string]interface {}

goroutine 20 [running]:
testing.tRunner.func1.1(0x17c6c20, 0xc00015f810)
	C:/Users/ahstn/sdk/go1.15.6/src/testing/testing.go:1072 +0x310
testing.tRunner.func1(0xc0002a5e00)
	C:/Users/ahstn/sdk/go1.15.6/src/testing/testing.go:1075 +0x43a
panic(0x17c6c20, 0xc00015f810)
	C:/Users/ahstn/sdk/go1.15.6/src/runtime/panic.go:969 +0x1c7
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x1770060, 0xc0001577a0, 0xc00005b788, 0xc0002c57d0)
	C:/Users/ahstn/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/runtime/converter.go:466 +0x4e6
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x17d65c0, 0xc0002c5230, 0x1935434, 0x8)
	C:/Users/ahstn/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/runtime/converter.go:450 +0x157
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x17d65c0, 0xc0002c51d0, 0xc00005b960, 0x995279)
	C:/Users/ahstn/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/runtime/converter.go:450 +0x157
k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
	C:/Users/ahstn/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/runtime/converter.go:435
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy(0xc0000c0670, 0x2)
	C:/Users/ahstn/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/apis/meta/v1/unstructured/unstructured.go:146 +0x7d
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopyObject(0xc0000c0670, 0xc00005bbc8, 0xe82779)
	C:/Users/ahstn/go/pkg/mod/k8s.io/apimachinery@v0.18.14/pkg/apis/meta/v1/unstructured/zz_generated.deepcopy.go:36 +0x32
k8s.io/client-go/testing.(*tracker).add(0xc0002c2f00, 0x0, 0x0, 0x1932fb3, 0x2, 0xc0002ea164, 0x4, 0x1a9ade0, 0xc0000c0670, 0x193494a, ...)
	C:/Users/ahstn/go/pkg/mod/k8s.io/client-go@v0.18.14/testing/fixture.go:391 +0x129
k8s.io/client-go/testing.(*tracker).Add(0xc0002c2f00, 0x1a9ade0, 0xc0000c0670, 0x3, 0x1a91ae0)
	C:/Users/ahstn/go/pkg/mod/k8s.io/client-go@v0.18.14/testing/fixture.go:351 +0x36d
k8s.io/client-go/dynamic/fake.NewSimpleDynamicClient(0xc0002e4230, 0xc0002fbf60, 0x1, 0x1, 0xc0001edf28)
	C:/Users/ahstn/go/pkg/mod/k8s.io/client-go@v0.18.14/dynamic/fake/simple.go:44 +0x5bb
github.com/ahstn/karetaker/pkg/kubernetes.TestResourcesInUse(0xc0002a5e00)
	C:/Users/ahstn/git/karetaker/pkg/kubernetes/resources_test.go:61 +0x787
testing.tRunner(0xc0002a5e00, 0x19cbd50)
	C:/Users/ahstn/sdk/go1.15.6/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/Users/ahstn/sdk/go1.15.6/src/testing/testing.go:1168 +0x2b3
```

**`go.mod` versions:**
```go
go 1.14

require (
	k8s.io/api v0.18.14
	k8s.io/apimachinery v0.18.14
	k8s.io/client-go v0.18.14
	k8s.io/utils v0.0.0-20200327001022-6496210b90e8 // indirect
)
```

FWIW: `v0.20.0` also has the same issue (as expected I guess)

**Comment by liggitt** [comment]
The only array type expected is `[]interface{}`
