### ISSUE TITLE
Upgrade from 0.19.x to 0.20.x leads to fakedynamic.NewSimpleDynamicClient panic

### ISSUE THREAD

**Issue by zbindenren** [kubernetes/client-go#914]
With 0.19.x this code works:

```go
func TestArgo(t *testing.T) {
	c := fakedynamic.NewSimpleDynamicClient(runtime.NewScheme()).Resource(
		schema.GroupVersionResource{
			Group:    "argoproj.io",
			Version:  "v1alpha1",
			Resource: "applications",
		},
	)

	c.Namespace("default").List(context.Background(), metav1.ListOptions{})
}
```

When I update to 0.20.x I get a panic:

```
=== RUN   TestArgo
--- FAIL: TestArgo (0.00s)
panic: coding error: you must register resource to list kind for every resource you're going to LIST when creating the client.  See NewSimpleDynamicClientWithCustomListKinds or register the list into the scheme: argoproj.io/v1alpha1, Resource=applications out of map[] [recovered]
        panic: coding error: you must register resource to list kind for every resource you're going to LIST when creating the client.  See NewSimpleDynamicClientWithCustomListKinds or register the list into the scheme: argoproj.io/v1alpha1, Resource=applications out of map[]

goroutine 7 [running]:
testing.tRunner.func1.1(0x1347360, 0xc0003c8f40)
        /home/rz/.gimme/versions/go1.15.5.linux.amd64/src/testing/testing.go:1072 +0x30d
testing.tRunner.func1(0xc00042fe00)
        /home/rz/.gimme/versions/go1.15.5.linux.amd64/src/testing/testing.go:1075 +0x41a
panic(0x1347360, 0xc0003c8f40)
        /home/rz/.gimme/versions/go1.15.5.linux.amd64/src/runtime/panic.go:969 +0x1b9
k8s.io/client-go/dynamic/fake.(*dynamicResourceClient).List(0xc000492540, 0x16aa440, 0xc000044128, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/rz/golang/pkg/mod/k8s.io/client-go@v0.20.1/dynamic/fake/simple.go:317 +0xcbf
git.pnet.ch/kubernetes/namespace-creator/pkg/kubernetes.TestArgo(0xc00042fe00)
        /home/rz/repos/git.pnet.ch/kubernetes/namespace-creator/pkg/kubernetes/client_test.go:66 +0x1f5
testing.tRunner(0xc00042fe00, 0x15a3508)
        /home/rz/.gimme/versions/go1.15.5.linux.amd64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
        /home/rz/.gimme/versions/go1.15.5.linux.amd64/src/testing/testing.go:1168 +0x2b3
FAIL    git.pnet.ch/kubernetes/namespace-creator/pkg/kubernetes 0.015s
FAIL
```

**Comment by kouvaliasnick** [comment]
I have exactly the same issue. Has anyone managed to get insights on this?
I have just found the [related commit ](https://github.com/kubernetes/client-go/commit/20c034c1785b34a893f7f96d91e5b849ac52ff31) and I will investigate more tomorrow

**Comment by benmoss** [comment]
same issue: https://github.com/kubernetes/client-go/issues/949

**Comment by benmoss** [comment]
There's an explanation from @deads2k here https://github.com/kubernetes/client-go/issues/949#issuecomment-811154420
