### ISSUE TITLE
v0.21.0 Dynamic fake client error: panic: cannot deep copy []map[string]interface {}

### ISSUE THREAD

**Issue by nicolehanjing** [kubernetes/client-go#979]
**Issue:**
When using the `k8s.io/client-go/dynamic/fake` client for unit tests, I get the following error if the unstructured "Object" field contains any []map[string]interface{}.
I tried wrapping `map[string]interface{}` items in a `[]interface{}` field, but it does not work.
p.s. `Object: map[string]interface{}` cannot be wrapped with `[]interface{}`

```
panic: cannot deep copy []map[string]interface {} [recovered]
	panic: cannot deep copy []map[string]interface {}
```
**Example:**
```
import (
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/client-go/dynamic/fake"
	"testing"
)

func newUnstructured(apiVersion, kind, namespace, name string) *unstructured.Unstructured {
	u := &unstructured.Unstructured{
		Object: map[string]interface{}{
			"apiVersion": apiVersion,
			"kind":       kind,
			"metadata": []interface{}{
				map[string]interface{}{
					"namespace": namespace,
					"name":      name,
				},
			},
			"spec": []interface{}{
				map[string]interface{}{
					"pros": []interface{}{
						[]map[string]interface{}{
							{
								"pro1": "test",
								"pro2": "test",
							},
						},
					},
				},
			},
		},
	}
	return u
}

func TestResourcesInUse(t *testing.T) {
	scheme := runtime.NewScheme()
	fake.NewSimpleDynamicClient(scheme, newUnstructured("group/version", "CustomResource", testClusterNameSpace, "node-name"))
         
        // OR
        fake.NewSimpleDynamicClientWithCustomListKinds(scheme,
		map[schema.GroupVersionResource]string{
			{Group: "group", Version: "version", Resource: "thekinds"}: "TheKindList",
		},
		newUnstructured("group/version", "TheKind", testClusterNameSpace, "node-name"),
        )
}
```
**Full stack trace:**
```
--- FAIL: TestGetRouteName (0.00s)
panic: cannot deep copy []map[string]interface {} [recovered]
	panic: cannot deep copy []map[string]interface {}

goroutine 9 [running]:
testing.tRunner.func1.1(0x24c1040, 0xc0003e4a10)
	/usr/local/go/src/testing/testing.go:1076 +0x30d
testing.tRunner.func1(0xc000582900)
	/usr/local/go/src/testing/testing.go:1079 +0x41a
panic(0x24c1040, 0xc0003e4a10)
	/usr/local/go/src/runtime/panic.go:969 +0x175
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x23f5060, 0xc000611480, 0x1, 0xc0003e4a00)
	/Users/nicolehan/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/runtime/converter.go:469 +0x4e6
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x23ed1a0, 0xc0006114a0, 0xc0004651e0, 0xc000172de0)
	/Users/nicolehan/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/runtime/converter.go:463 +0x34b
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x24da0c0, 0xc0000bdd40, 0x2728bee, 0x8)
	/Users/nicolehan/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/runtime/converter.go:453 +0x157
k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x24da0c0, 0xc0000bdbc0, 0xc0003643b0, 0x9)
	/Users/nicolehan/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/runtime/converter.go:453 +0x157
k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
	/Users/nicolehan/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/runtime/converter.go:438
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy(0xc00044f140, 0x8)
	/Users/nicolehan/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/apis/meta/v1/unstructured/unstructured.go:146 +0x75
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopyObject(0xc00044f140, 0x9, 0x7400000000)
	/Users/nicolehan/go/pkg/mod/k8s.io/apimachinery@v0.21.0/pkg/apis/meta/v1/unstructured/zz_generated.deepcopy.go:36 +0x2b
k8s.io/client-go/testing.(*tracker).add(0xc00007fea0, 0x273bfb9, 0xe, 0x273bfc8, 0x8, 0xc0003643b0, 0x9, 0x29243c0, 0xc00044f140, 0x2739ab2, ...)
	/Users/nicolehan/go/pkg/mod/k8s.io/client-go@v0.21.0/testing/fixture.go:376 +0x11a
k8s.io/client-go/testing.(*tracker).Add(0xc00007fea0, 0x29243c0, 0xc00044f140, 0xc000582c00, 0x3)
	/Users/nicolehan/go/pkg/mod/k8s.io/client-go@v0.21.0/testing/fixture.go:336 +0x36d
k8s.io/client-go/dynamic/fake.NewSimpleDynamicClientWithCustomListKinds(0xc000783030, 0xc000088c90, 0xc0004efc50, 0x1, 0x1, 0x15)
	/Users/nicolehan/go/pkg/mod/k8s.io/client-go@v0.21.0/dynamic/fake/simple.go:81 +0xc94
k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual.initRouteTest(0xc000507f18, 0x1058ca5)
	/Users/nicolehan/go/src/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/route_test.go:79 +0x234
k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual.TestGetRouteName(0xc000582900)
	/Users/nicolehan/go/src/k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/route_test.go:107 +0x34
testing.tRunner(0xc000582900, 0x27e4d08)
	/usr/local/go/src/testing/testing.go:1127 +0xef
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1178 +0x386
```

**go.mod versions:**
```
go 1.15

require (
	k8s.io/api v0.21.0
	k8s.io/apiextensions-apiserver v0.21.0
	k8s.io/apimachinery v0.21.0
	k8s.io/client-go v0.21.0
)
```

**Comment by jlucktay** [comment]
This looks similar to #913.
