### ISSUE TITLE
SharedInformer sometime panic with nil

### ISSUE THREAD

**Issue by Baojizhong** [kubernetes/client-go#991]
My Code Like
```
informer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
  AddFunc: func(obj interface{}) {
	  c := *(obj.(*v1beta1.Cluster))
	  ci.AddClusterResourceInformer(c)
  },
  UpdateFunc: func(oldObj, newObj interface{}) {
	  newCluster := *(newObj.(*v1beta1.Cluster))
	  oldCluster := *(oldObj.(*v1beta1.Cluster))
	  if oldCluster.Spec.KubeConfig != newCluster.Spec.KubeConfig {
		  ci.UpdateClusterResourceInformer(newCluster)
	  }
  },
  DeleteFunc: func(obj interface{}) {
	  c := *(obj.(*v1beta1.Cluster))
	  ci.RemoveClusterResourceInformer(c)
  },
})
go informer.Informer().Run(make(chan struct{}))
informerFactory.Start(make(chan struct{}))
informerFactory.WaitForCacheSync(make(chan struct{}))
```
sometime the code will panic , error msg 
```
goroutine 386 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x14b5de0, 0x20a5350)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/runtime/runtime.go:51 +0x89
panic(0x14b5de0, 0x20a5350)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0x400, 0x400, 0x17)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a/tools/cache/shared_informer.go:606 +0xa1
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc00ade5e18, 0xed7a33e37, 0x0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:284 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a/tools/cache/shared_informer.go:601 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0048ecf60)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00ade5f60, 0xdf8475800, 0x0, 0x1, 0xc003d6f680)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:153 +0x105
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc00c511200)
	/go/pkg/mod/k8s.io/client-go@v0.0.0-20190918200256-06eb1244587a/tools/cache/shared_informer.go:599 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc00a8be4c0, 0xc00a80b0c0)
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190817020851-f2f3a405f61d/pkg/util/wait/wait.go:69 +0x65
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10a7ea1]
```
and have some warning like
```
E0624 17:17:06.672830       1 shared_informer.go:611] unrecognized notification: <nil>
E0624 17:17:06.908249       1 shared_informer.go:611] unrecognized notification: <nil>
E0624 17:17:08.101652       1 shared_informer.go:611] unrecognized notification: <nil>
```
my client-go version v0.0.0-20190918200256-06eb1244587a

**Comment by Baojizhong** [comment]
i got reason

**Comment by Seryta** [comment]
Can you tell me why? I encountered the same mistake

**Comment by Seryta** [comment]
Can you tell me why? I encountered the same mistake

**Comment by Baojizhong** [comment]
> Can you tell me why? I encountered the same mistake

factory.Start() contains informer.Run()
do not use both of them.

**Comment by Baojizhong** [comment]
> Can you tell me why? I encountered the same mistake

factory.Start() contains informer.Run()
do not use both of them.

**Comment by Seryta** [comment]
OK, thanks
